export const productActionTypes = {
	FETCH_PRODUCTS: "FETCH_PRODUCTS",
	SET_PRODUCTS: "SET_PRODUCTS",
	SELECTED_PRODUCT: "SELECTED_PRODUCT",
	REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
	HIDE_PRODUCT: "HIDE_PRODUCT",
	DELETE_PRODUCT: "DELETE_PRODUCT",
	UPDATE_PRODUCT: "EDIT_PRODUCT",
	CREATE_PRODUCT: "CREATE_PRODUCT",
	UPDATED_DATE_AFTER_ORDER: "UPDATED_DATE_AFTER_ORDER",
};
