export const styleActionTypes = {
	DISPLAY_LOGIN_PANEL: "DISPLAY_LOGIN_PANEL",
	DISPLAY_SIGNUP_PANEL: "DISPLAY_SIGNUP_PANEL",
	DISPLAY_USERMENU_ITEM: "DISPLAY_USERMENU_ITEM",
	DISPLAY_LOGEDIN_USER_PANEL: "DISPLAY_LOGEDIN_USER_PANEL",
	DISPLAY_ADMIN_MENU_ITEM: "DISPLAY_ADMIN_MENU_ITEM",
};
